return {
  schemaVersion = 2,
  metadataFieldsForPhotos = {
    {
      id = "masterTaxonId",
      title = "Master-Taxon-ID",
      dataType = "string",
      searchable = true,
      browsable = true,
    },
    {
      id = "projectTaxonId",
      title = "Arten-Explorer-ID",
      dataType = "string",
      searchable = true,
      browsable = true,
    },
    {
      id = "germanName",
      title = "Deutscher Artname",
      dataType = "string",
      searchable = true,
      browsable = true,
    },
    {
      id = "englishName",
      title = "Englischer Artname",
      dataType = "string",
      searchable = true,
      browsable = true,
    },
    {
      id = "scientificName",
      title = "Wissenschaftlicher Artname",
      dataType = "string",
      searchable = true,
      browsable = true,
    },
    {
      id = "taxonRank",
      title = "Taxonomischer Rang",
      dataType = "string",
      searchable = true,
      browsable = true,
    },
    {
      id = "taxonomyPath",
      title = "Taxonomiepfad",
      dataType = "string",
      searchable = true,
      browsable = false,
    },
    {
      id = "taxonomyClass",
      title = "Klasse (wissenschaftlich)",
      dataType = "string",
      searchable = true,
      browsable = true,
    },
    {
      id = "taxonomyFamily",
      title = "Familie (wissenschaftlich)",
      dataType = "string",
      searchable = true,
      browsable = true,
    },
    {
      id = "taxonomyGenus",
      title = "Gattung (wissenschaftlich)",
      dataType = "string",
      searchable = true,
      browsable = true,
    },
    {
      id = "referenceImage",
      title = "Art-Referenzbild",
      dataType = "enum",
      values = {
        { value = "no", title = "Nein" },
        { value = "yes", title = "Ja" },
      },
      searchable = true,
      browsable = true,
    },
    {
      id = "assignedAt",
      title = "Taxonomie zugewiesen am",
      dataType = "string",
      searchable = false,
      browsable = false,
    },
  },
}
