name: Update IUCN Data

on:
  schedule:
    - cron: '0 0 1 * *'  # jeden Monat am 1.
  workflow_dispatch:     # manuell ausführbar

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          npm install

      - name: Run Update Script
        env:
          IUCN_TOKEN: ${{ secrets.IUCN_TOKEN }}
        run: node update.js

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add api/speciesData.json
          git commit -m "Update IUCN data"
          git push
